### ISSUE TITLE
Undefined constant "LOG_LOCAL0" in config.php on line 159

### ISSUE THREAD

**Issue by jabcreations** [falon/RBL#3]
My local development machine is Windows 10 and I copied the files to an rbl/ directory and executed index.php in the browser. I had to create a config.php from the demonstration copy, that is fine.

However I'm getting this message:
Undefined constant "LOG_LOCAL0" in config.php on line 159

I have no idea what LOG_LOCAL0 is supposed to be and there are three references in the GIT search that do not look like any kind of declaration. Searching outside of GIT it looks like something from WordPress.

Whatever it's intended to be it represents some kind of string (most likely). What is a hot fix for this?

I set $fac = false;//LOG_LOCAL0; and then the form finally came up. I submitted the form and got the following error:
require_once(vendor/autoload.php): Failed to open stream

Am I correct in presuming that this is provided by one of the nearly half dozen prerequisites?

**Comment by falon** [comment]
Hello @jabcreations,
  `LOG_LOCAL0` is a syslog constant. It's supported only in Linux as [described here](https://www.php.net/manual/en/function.syslog.php).

Even in the more basic working mode you need the _dautkom/php.ipv4_ module (`composer require dautkom/php.ipv4`).
I don't know how to install it in Windows using `composer`. I never tried a Windows setup.

I'm sorry, I know there are a lot of requisites. For a quick installation I suggest a Centos/Red Hat EL8 environment with the dnf setup.

**Comment by jabcreations** [comment]
Is syslog included by default in one of the listed requisites or should it be added to the documentation?

I've been poking around different PHP scripts looking for a quick way to ping multiple DNSBL servers without the excessive delays.

**Comment by falon** [comment]
I should add in documentation that I tried this setup only in Centos/Red Hat EL8 systems.
In Linux, the facility syslog constants are included by default. A Windows setup could be hard...

**Comment by jabcreations** [comment]
When you work on the prerequisites basically setup a server from scratch. I write all my software from scratch though I do look at what other people write because I'm not all-powerful/all-knowing/etc. The fewer dependencies the better the software is written though I still get the whole time constraint bit too.

I've managed to find how the look ups work and am working to refine the script to determine the quickest way to scan the most servers. I'll likely post my revision of that script, you can find the original here: https://github.com/jaywire/RBL-Checker

You don't need to do anything on my behalf here, I'm just trying to be helpful. I enjoy getting more data sets from various scenarios such as different server environments and client responses, makes my code stronger.
